CREATE TABLE [bd].[DiseaseMap_107] (
    [OBJECTID]              INT               NOT NULL,
    [Urban_GridCode]        SMALLINT          NULL,
    [Sanitation_Level]      INT               NULL,
    [Water_Quality]         NUMERIC (38, 8)   NULL,
    [Seasonality_Zone]      SMALLINT          NULL,
    [Developed]             NUMERIC (38, 8)   NULL,
    [D63_prev]              NUMERIC (38, 8)   NULL,
    [D51_prev]              NUMERIC (38, 8)   NULL,
    [D82_prev]              NUMERIC (38, 8)   NULL,
    [D64_prev]              NUMERIC (38, 8)   NULL,
    [D24_prev]              NUMERIC (38, 8)   NULL,
    [D52_prev]              NUMERIC (38, 8)   NULL,
    [D60_prev]              NUMERIC (38, 8)   NULL,
    [D15_prev]              NUMERIC (38, 8)   NULL,
    [D3_prev]               NUMERIC (38, 8)   NULL,
    [D20_prev]              NUMERIC (38, 8)   NULL,
    [D25_prev]              NUMERIC (38, 8)   NULL,
    [D98_prev]              NUMERIC (38, 8)   NULL,
    [D90_prev]              NUMERIC (38, 8)   NULL,
    [D109_prev]             NUMERIC (38, 8)   NULL,
    [D48_prev]              NUMERIC (38, 8)   NULL,
    [D77_prev]              NUMERIC (38, 8)   NULL,
    [D83_prev]              NUMERIC (38, 8)   NULL,
    [D36_prev]              NUMERIC (38, 8)   NULL,
    [D75_prev]              NUMERIC (38, 8)   NULL,
    [D21_prev]              NUMERIC (38, 8)   NULL,
    [D85_prev]              NUMERIC (38, 8)   NULL,
    [D68_prev]              NUMERIC (38, 8)   NULL,
    [D42_prev]              NUMERIC (38, 8)   NULL,
    [D35_prev]              NUMERIC (38, 8)   NULL,
    [D87_prev]              NUMERIC (38, 8)   NULL,
    [D6_prev]               NUMERIC (38, 8)   NULL,
    [D46_prev]              NUMERIC (38, 8)   NULL,
    [D8_prev]               NUMERIC (38, 8)   NULL,
    [D62_prev]              NUMERIC (38, 8)   NULL,
    [D55_prev]              NUMERIC (38, 8)   NULL,
    [D22_prev]              NUMERIC (38, 8)   NULL,
    [D23_prev]              NUMERIC (38, 8)   NULL,
    [D78_prev]              NUMERIC (38, 8)   NULL,
    [D44_prev]              NUMERIC (38, 8)   NULL,
    [D38_prev]              NUMERIC (38, 8)   NULL,
    [D74_prev]              NUMERIC (38, 8)   NULL,
    [D91_prev]              NUMERIC (38, 8)   NULL,
    [D72_prev]              NUMERIC (38, 8)   NULL,
    [D31_prev]              NUMERIC (38, 8)   NULL,
    [D41_prev]              NUMERIC (38, 8)   NULL,
    [D70_prev]              NUMERIC (38, 8)   NULL,
    [D27_prev]              NUMERIC (38, 8)   NULL,
    [D101_prev]             NUMERIC (38, 8)   NULL,
    [D104_prev]             NUMERIC (38, 8)   NULL,
    [D18_prev]              NUMERIC (38, 8)   NULL,
    [D61_prev]              NUMERIC (38, 8)   NULL,
    [D108_prev]             NUMERIC (38, 8)   NULL,
    [D54_prev]              NUMERIC (38, 8)   NULL,
    [D53_prev]              NUMERIC (38, 8)   NULL,
    [D7_prev]               NUMERIC (38, 8)   NULL,
    [D45_prev]              NUMERIC (38, 8)   NULL,
    [D1_prev]               NUMERIC (38, 8)   NULL,
    [D73_prev]              NUMERIC (38, 8)   NULL,
    [D39_prev]              NUMERIC (38, 8)   NULL,
    [D86_prev]              NUMERIC (38, 8)   NULL,
    [D71_prev]              NUMERIC (38, 8)   NULL,
    [D67_prev]              NUMERIC (38, 8)   NULL,
    [D29_prev]              NUMERIC (38, 8)   NULL,
    [D17_prev]              NUMERIC (38, 8)   NULL,
    [D47_prev]              NUMERIC (38, 8)   NULL,
    [D81_prev]              NUMERIC (38, 8)   NULL,
    [D14_prev]              NUMERIC (38, 8)   NULL,
    [D34_prev]              NUMERIC (38, 8)   NULL,
    [D10_prev]              NUMERIC (38, 8)   NULL,
    [D57_prev]              NUMERIC (38, 8)   NULL,
    [D103_prev]             NUMERIC (38, 8)   NULL,
    [D92_prev]              NUMERIC (38, 8)   NULL,
    [D13_prev]              NUMERIC (38, 8)   NULL,
    [D26_prev]              NUMERIC (38, 8)   NULL,
    [D65_prev]              NUMERIC (38, 8)   NULL,
    [D32_prev]              NUMERIC (38, 8)   NULL,
    [D84_prev]              NUMERIC (38, 8)   NULL,
    [D37_prev]              NUMERIC (38, 8)   NULL,
    [D28_prev]              NUMERIC (38, 8)   NULL,
    [D66_prev]              NUMERIC (38, 8)   NULL,
    [D59_prev]              NUMERIC (38, 8)   NULL,
    [D110_prev]             NUMERIC (38, 8)   NULL,
    [D9_prev]               NUMERIC (38, 8)   NULL,
    [D30_prev]              NUMERIC (38, 8)   NULL,
    [D33_prev]              NUMERIC (38, 8)   NULL,
    [D19_prev]              NUMERIC (38, 8)   NULL,
    [D4_prev]               NUMERIC (38, 8)   NULL,
    [D50_prev]              NUMERIC (38, 8)   NULL,
    [D11_prev]              NUMERIC (38, 8)   NULL,
    [D16_prev]              NUMERIC (38, 8)   NULL,
    [D89_prev]              NUMERIC (38, 8)   NULL,
    [D80_prev]              NUMERIC (38, 8)   NULL,
    [D12_prev]              NUMERIC (38, 8)   NULL,
    [D2_prev]               NUMERIC (38, 8)   NULL,
    [D40_prev]              NUMERIC (38, 8)   NULL,
    [D69_prev]              NUMERIC (38, 8)   NULL,
    [D88_prev]              NUMERIC (38, 8)   NULL,
    [D43_prev]              NUMERIC (38, 8)   NULL,
    [D58_prev]              NUMERIC (38, 8)   NULL,
    [D76_prev]              NUMERIC (38, 8)   NULL,
    [D107_prev]             NUMERIC (38, 8)   NULL,
    [D49_prev]              NUMERIC (38, 8)   NULL,
    [D95_prev]              NUMERIC (38, 8)   NULL,
    [D56_prev]              NUMERIC (38, 8)   NULL,
    [D5_prev]               NUMERIC (38, 8)   NULL,
    [Country_Water_Quality] SMALLINT          NULL,
    [created_user]          VARCHAR (255)     NULL,
    [created_date]          DATETIME2 (7)     NULL,
    [last_edited_user]      VARCHAR (255)     NULL,
    [last_edited_date]      DATETIME2 (7)     NULL,
    [Shape.STArea()]        NUMERIC (38, 8)   NULL,
    [Shape.STLength()]      NUMERIC (38, 8)   NULL, 
    [GEOGRAPHY] [sys].[geography] NULL, 
    CONSTRAINT [PK_DiseaseMap_107] PRIMARY KEY ([OBJECTID])
);

