//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels.George
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DiseasesAPIEntities : DbContext
    {
        public DiseasesAPIEntities()
            : base("name=DiseasesAPIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<string> usp_HcwGetDiseaseIntroduction(Nullable<int> diseaseId)
        {
            var diseaseIdParameter = diseaseId.HasValue ?
                new ObjectParameter("DiseaseId", diseaseId) :
                new ObjectParameter("DiseaseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_HcwGetDiseaseIntroduction", diseaseIdParameter);
        }
    
        public virtual ObjectResult<string> usp_PullRegularTables(string jsonSymptoms, string jsonDiseases, string jsonGeorgeMessaging, string jsonGeorgeModifiers, string jsonInterventionCategory)
        {
            var jsonSymptomsParameter = jsonSymptoms != null ?
                new ObjectParameter("JsonSymptoms", jsonSymptoms) :
                new ObjectParameter("JsonSymptoms", typeof(string));
    
            var jsonDiseasesParameter = jsonDiseases != null ?
                new ObjectParameter("JsonDiseases", jsonDiseases) :
                new ObjectParameter("JsonDiseases", typeof(string));
    
            var jsonGeorgeMessagingParameter = jsonGeorgeMessaging != null ?
                new ObjectParameter("JsonGeorgeMessaging", jsonGeorgeMessaging) :
                new ObjectParameter("JsonGeorgeMessaging", typeof(string));
    
            var jsonGeorgeModifiersParameter = jsonGeorgeModifiers != null ?
                new ObjectParameter("JsonGeorgeModifiers", jsonGeorgeModifiers) :
                new ObjectParameter("JsonGeorgeModifiers", typeof(string));
    
            var jsonInterventionCategoryParameter = jsonInterventionCategory != null ?
                new ObjectParameter("JsonInterventionCategory", jsonInterventionCategory) :
                new ObjectParameter("JsonInterventionCategory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_PullRegularTables", jsonSymptomsParameter, jsonDiseasesParameter, jsonGeorgeMessagingParameter, jsonGeorgeModifiersParameter, jsonInterventionCategoryParameter);
        }
    }
}
