using System;
using System.Collections.Generic;

namespace Biod.Api.Core.Models
{
    public partial class DiseaseConditionsGcs
    {
        public int Objectid { get; set; }
        public short? UrbanGridCode { get; set; }
        public int? SanitationLevel { get; set; }
        public decimal? WaterQuality { get; set; }
        public short? SeasonalityZone { get; set; }
        public decimal? Developed { get; set; }
        public decimal? D63Prev { get; set; }
        public decimal? D51Prev { get; set; }
        public decimal? D82Prev { get; set; }
        public decimal? D64Prev { get; set; }
        public decimal? D24Prev { get; set; }
        public decimal? D52Prev { get; set; }
        public decimal? D60Prev { get; set; }
        public decimal? D15Prev { get; set; }
        public decimal? D3Prev { get; set; }
        public decimal? D20Prev { get; set; }
        public decimal? D25Prev { get; set; }
        public decimal? D98Prev { get; set; }
        public decimal? D90Prev { get; set; }
        public decimal? D109Prev { get; set; }
        public decimal? D48Prev { get; set; }
        public decimal? D77Prev { get; set; }
        public decimal? D83Prev { get; set; }
        public decimal? D36Prev { get; set; }
        public decimal? D75Prev { get; set; }
        public decimal? D21Prev { get; set; }
        public decimal? D85Prev { get; set; }
        public decimal? D68Prev { get; set; }
        public decimal? D42Prev { get; set; }
        public decimal? D35Prev { get; set; }
        public decimal? D87Prev { get; set; }
        public decimal? D6Prev { get; set; }
        public decimal? D46Prev { get; set; }
        public decimal? D8Prev { get; set; }
        public decimal? D62Prev { get; set; }
        public decimal? D55Prev { get; set; }
        public decimal? D22Prev { get; set; }
        public decimal? D23Prev { get; set; }
        public decimal? D78Prev { get; set; }
        public decimal? D44Prev { get; set; }
        public decimal? D38Prev { get; set; }
        public decimal? D74Prev { get; set; }
        public decimal? D91Prev { get; set; }
        public decimal? D72Prev { get; set; }
        public decimal? D31Prev { get; set; }
        public decimal? D41Prev { get; set; }
        public decimal? D70Prev { get; set; }
        public decimal? D27Prev { get; set; }
        public decimal? D101Prev { get; set; }
        public decimal? D104Prev { get; set; }
        public decimal? D18Prev { get; set; }
        public decimal? D61Prev { get; set; }
        public decimal? D108Prev { get; set; }
        public decimal? D54Prev { get; set; }
        public decimal? D53Prev { get; set; }
        public decimal? D7Prev { get; set; }
        public decimal? D45Prev { get; set; }
        public decimal? D1Prev { get; set; }
        public decimal? D73Prev { get; set; }
        public decimal? D39Prev { get; set; }
        public decimal? D86Prev { get; set; }
        public decimal? D71Prev { get; set; }
        public decimal? D67Prev { get; set; }
        public decimal? D29Prev { get; set; }
        public decimal? D17Prev { get; set; }
        public decimal? D47Prev { get; set; }
        public decimal? D81Prev { get; set; }
        public decimal? D14Prev { get; set; }
        public decimal? D34Prev { get; set; }
        public decimal? D10Prev { get; set; }
        public decimal? D57Prev { get; set; }
        public decimal? D103Prev { get; set; }
        public decimal? D92Prev { get; set; }
        public decimal? D13Prev { get; set; }
        public decimal? D26Prev { get; set; }
        public decimal? D65Prev { get; set; }
        public decimal? D32Prev { get; set; }
        public decimal? D84Prev { get; set; }
        public decimal? D37Prev { get; set; }
        public decimal? D28Prev { get; set; }
        public decimal? D66Prev { get; set; }
        public decimal? D59Prev { get; set; }
        public decimal? D110Prev { get; set; }
        public decimal? D9Prev { get; set; }
        public decimal? D30Prev { get; set; }
        public decimal? D33Prev { get; set; }
        public decimal? D19Prev { get; set; }
        public decimal? D4Prev { get; set; }
        public decimal? D50Prev { get; set; }
        public decimal? D11Prev { get; set; }
        public decimal? D16Prev { get; set; }
        public decimal? D89Prev { get; set; }
        public decimal? D80Prev { get; set; }
        public decimal? D12Prev { get; set; }
        public decimal? D2Prev { get; set; }
        public decimal? D40Prev { get; set; }
        public decimal? D69Prev { get; set; }
        public decimal? D88Prev { get; set; }
        public decimal? D43Prev { get; set; }
        public decimal? D58Prev { get; set; }
        public decimal? D76Prev { get; set; }
        public decimal? D107Prev { get; set; }
        public decimal? D49Prev { get; set; }
        public decimal? D95Prev { get; set; }
        public decimal? D56Prev { get; set; }
        public decimal? D5Prev { get; set; }
        public short? CountryWaterQuality { get; set; }
        public decimal? ShapeStarea { get; set; }
        public decimal? ShapeStlength { get; set; }
    }
}
