//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetRole()
        {
            this.Xtbl_Role_Disease_Relevance = new HashSet<Xtbl_Role_Disease_Relevance>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string NotificationDescription { get; set; }
        public bool IsPublic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Xtbl_Role_Disease_Relevance> Xtbl_Role_Disease_Relevance { get; set; }
    }
}
