//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransLog
    {
        public string UserId { get; set; }
        public System.DateTime ModifiedUTCDatetime { get; set; }
        public string ModificationDescription { get; set; }
    }
}
