//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvw_DiseaseRelevanceByRole
    {
        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public int DiseaseId { get; set; }
        public string DiseaseName { get; set; }
        public int RelevanceId { get; set; }
        public string RelevanceDescription { get; set; }
        public int StateId { get; set; }
        public string StateDescription { get; set; }
    }
}
