//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xtbl_User_Disease_Relevance
    {
        public string UserId { get; set; }
        public int DiseaseId { get; set; }
        public int RelevanceId { get; set; }
        public int StateId { get; set; }
    
        public virtual RelevanceState RelevanceState { get; set; }
        public virtual RelevanceType RelevanceType { get; set; }
    }
}
