//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Surveillance.Zebra.SyncConsole.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BiodSurveillanceDataModelEntities : DbContext
    {
        public BiodSurveillanceDataModelEntities()
            : base("name=BiodSurveillanceDataModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disease> Diseases { get; set; }
        public virtual DbSet<Geoname> Geonames { get; set; }
        public virtual DbSet<ArticleFeed> ArticleFeeds { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventCreationReason> EventCreationReasons { get; set; }
        public virtual DbSet<EventPriority> EventPriorities { get; set; }
        public virtual DbSet<HamType> HamTypes { get; set; }
        public virtual DbSet<LastSuggestedEventPullDate> LastSuggestedEventPullDates { get; set; }
        public virtual DbSet<ProcessedArticle> ProcessedArticles { get; set; }
        public virtual DbSet<SuggestedEvent> SuggestedEvents { get; set; }
        public virtual DbSet<Xtbl_Article_Location_Disease> Xtbl_Article_Location_Disease { get; set; }
        public virtual DbSet<Xtbl_Event_Location> Xtbl_Event_Location { get; set; }
        public virtual DbSet<Xtbl_RelatedArticles> Xtbl_RelatedArticles { get; set; }
        public virtual DbSet<Xtbl_SuggestedEvent_Reason> Xtbl_SuggestedEvent_Reason { get; set; }
    }
}
