//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Surveillance.Zebra.SyncConsole.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xtbl_SuggestedEvent_Reason
    {
        public long SuggestedEventId { get; set; }
        public string Reason { get; set; }
    
        public virtual SuggestedEvent SuggestedEvent { get; set; }
    }
}
