CREATE TABLE [zebra].[RelevanceState](
	[StateId] [int] NOT NULL,
	[Description] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_RelevanceState] PRIMARY KEY CLUSTERED 
(
	[StateId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO