CREATE TABLE [zebra].[RelevanceType](
	[RelevanceId] [int] NOT NULL,
	[Description] [nvarchar](256) NULL,
 CONSTRAINT [PK_RelevanceType] PRIMARY KEY CLUSTERED 
(
	[RelevanceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
