//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BdDataApi.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HealthmapEntities : DbContext
    {
        public HealthmapEntities()
            : base("name=HealthmapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<healthmapApi_getAlertArticles_sp_Result> healthmapApi_getAlertArticles_sp(Nullable<System.DateTime> lastUpdateTime)
        {
            var lastUpdateTimeParameter = lastUpdateTime.HasValue ?
                new ObjectParameter("LastUpdateTime", lastUpdateTime) :
                new ObjectParameter("LastUpdateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getAlertArticles_sp_Result>("healthmapApi_getAlertArticles_sp", lastUpdateTimeParameter);
        }
    
        public virtual ObjectResult<healthmapApi_getAlertArticlesArchive_sp_Result> healthmapApi_getAlertArticlesArchive_sp(Nullable<System.DateTime> lastUpdateTime)
        {
            var lastUpdateTimeParameter = lastUpdateTime.HasValue ?
                new ObjectParameter("LastUpdateTime", lastUpdateTime) :
                new ObjectParameter("LastUpdateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getAlertArticlesArchive_sp_Result>("healthmapApi_getAlertArticlesArchive_sp", lastUpdateTimeParameter);
        }
    
        public virtual ObjectResult<healthmapApi_getAlertArticlesContent_sp_Result> healthmapApi_getAlertArticlesContent_sp(Nullable<System.DateTime> lastUpdateTime)
        {
            var lastUpdateTimeParameter = lastUpdateTime.HasValue ?
                new ObjectParameter("LastUpdateTime", lastUpdateTime) :
                new ObjectParameter("LastUpdateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getAlertArticlesContent_sp_Result>("healthmapApi_getAlertArticlesContent_sp", lastUpdateTimeParameter);
        }
    
        public virtual ObjectResult<healthmapApi_getAlertArticlesContentArchive_sp_Result> healthmapApi_getAlertArticlesContentArchive_sp(Nullable<System.DateTime> lastUpdateTime)
        {
            var lastUpdateTimeParameter = lastUpdateTime.HasValue ?
                new ObjectParameter("LastUpdateTime", lastUpdateTime) :
                new ObjectParameter("LastUpdateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getAlertArticlesContentArchive_sp_Result>("healthmapApi_getAlertArticlesContentArchive_sp", lastUpdateTimeParameter);
        }
    
        public virtual ObjectResult<healthmapApi_getAlertLocationType_sp_Result> healthmapApi_getAlertLocationType_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getAlertLocationType_sp_Result>("healthmapApi_getAlertLocationType_sp");
        }
    
        public virtual ObjectResult<healthmapApi_getAlertSourceType_sp_Result> healthmapApi_getAlertSourceType_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getAlertSourceType_sp_Result>("healthmapApi_getAlertSourceType_sp");
        }
    
        public virtual ObjectResult<healthmapApi_getDisease_sp_Result> healthmapApi_getDisease_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getDisease_sp_Result>("healthmapApi_getDisease_sp");
        }
    
        public virtual ObjectResult<healthmapApi_getDiseaseAlertArticles_sp_Result> healthmapApi_getDiseaseAlertArticles_sp(Nullable<System.DateTime> lastUpdateTime)
        {
            var lastUpdateTimeParameter = lastUpdateTime.HasValue ?
                new ObjectParameter("LastUpdateTime", lastUpdateTime) :
                new ObjectParameter("LastUpdateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getDiseaseAlertArticles_sp_Result>("healthmapApi_getDiseaseAlertArticles_sp", lastUpdateTimeParameter);
        }
    
        public virtual ObjectResult<healthmapApi_getDiseaseAlertArticlesArchive_sp_Result> healthmapApi_getDiseaseAlertArticlesArchive_sp(Nullable<System.DateTime> lastUpdateTime)
        {
            var lastUpdateTimeParameter = lastUpdateTime.HasValue ?
                new ObjectParameter("LastUpdateTime", lastUpdateTime) :
                new ObjectParameter("LastUpdateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getDiseaseAlertArticlesArchive_sp_Result>("healthmapApi_getDiseaseAlertArticlesArchive_sp", lastUpdateTimeParameter);
        }
    
        public virtual ObjectResult<healthmapApi_getAlertArticlesContentUpdated_sp_Result> healthmapApi_getAlertArticlesContentUpdated_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getAlertArticlesContentUpdated_sp_Result>("healthmapApi_getAlertArticlesContentUpdated_sp");
        }
    
        public virtual ObjectResult<healthmapApi_getAlertArticlesUpdated_sp_Result> healthmapApi_getAlertArticlesUpdated_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getAlertArticlesUpdated_sp_Result>("healthmapApi_getAlertArticlesUpdated_sp");
        }
    
        public virtual ObjectResult<healthmapApi_getAlertLocationTypeUpdated_sp_Result> healthmapApi_getAlertLocationTypeUpdated_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getAlertLocationTypeUpdated_sp_Result>("healthmapApi_getAlertLocationTypeUpdated_sp");
        }
    
        public virtual ObjectResult<healthmapApi_getDiseaseAlertArticlesUpdated_sp_Result> healthmapApi_getDiseaseAlertArticlesUpdated_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getDiseaseAlertArticlesUpdated_sp_Result>("healthmapApi_getDiseaseAlertArticlesUpdated_sp");
        }
    
        public virtual ObjectResult<healthmapApi_getDiseaseUpdated_sp_Result> healthmapApi_getDiseaseUpdated_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getDiseaseUpdated_sp_Result>("healthmapApi_getDiseaseUpdated_sp");
        }
    
        public virtual ObjectResult<healthmapApi_getAlertSourceTypeUpdated_sp_Result> healthmapApi_getAlertSourceTypeUpdated_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<healthmapApi_getAlertSourceTypeUpdated_sp_Result>("healthmapApi_getAlertSourceTypeUpdated_sp");
        }
    
        [DbFunction("HealthmapEntities", "healthmap_getBdLocation_fn")]
        public virtual IQueryable<healthmap_getBdLocation_fn_Result> healthmap_getBdLocation_fn(string locationName)
        {
            var locationNameParameter = locationName != null ?
                new ObjectParameter("LocationName", locationName) :
                new ObjectParameter("LocationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<healthmap_getBdLocation_fn_Result>("[HealthmapEntities].[healthmap_getBdLocation_fn](@LocationName)", locationNameParameter);
        }
    }
}
