//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels.Surveillance
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoSurveillanceConfig
    {
        public int Id { get; set; }
        public int DiseaseId { get; set; }
        public Nullable<int> GeonameId { get; set; }
        public string Source { get; set; }
        public bool IncludeChildren { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual SurveillanceGeoname Geoname { get; set; }
    }
}
