//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels.Surveillance
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuggestedEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuggestedEvent()
        {
            this.ProcessedArticles = new HashSet<SurveillanceProcessedArticle>();
            this.Geonames = new HashSet<SurveillanceGeoname>();
            this.Xtbl_SuggestedEvent_Reason = new HashSet<Xtbl_SuggestedEvent_Reason>();
        }
    
        public string SuggestedEventId { get; set; }
        public string EventTitle { get; set; }
        public System.DateTime SystemLastModifiedDate { get; set; }
        public int DiseaseId { get; set; }
        public string Highlights { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveillanceProcessedArticle> ProcessedArticles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveillanceGeoname> Geonames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Xtbl_SuggestedEvent_Reason> Xtbl_SuggestedEvent_Reason { get; set; }
        public virtual Disease Disease { get; set; }
    }
}
