//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels.Surveillance
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveillanceGeoname
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveillanceGeoname()
        {
            this.GeonameAlternatenameEngs = new HashSet<GeonameAlternatenameEng>();
            this.Xtbl_Article_Location_Disease = new HashSet<SurveillanceXtbl_Article_Location_Disease>();
            this.Xtbl_Event_Location = new HashSet<SurveillanceXtbl_Event_Location>();
            this.ProcessedArticles = new HashSet<SurveillanceProcessedArticle>();
            this.SuggestedEvents = new HashSet<SuggestedEvent>();
            this.AutoSurveillanceConfigs = new HashSet<AutoSurveillanceConfig>();
        }
    
        public int GeonameId { get; set; }
        public string Name { get; set; }
        public Nullable<int> LocationType { get; set; }
        public Nullable<int> Admin1GeonameId { get; set; }
        public Nullable<int> CountryGeonameId { get; set; }
        public string DisplayName { get; set; }
        public string Alternatenames { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public string FeatureCode { get; set; }
        public string CountryName { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> Population { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeonameAlternatenameEng> GeonameAlternatenameEngs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveillanceXtbl_Article_Location_Disease> Xtbl_Article_Location_Disease { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveillanceXtbl_Event_Location> Xtbl_Event_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveillanceProcessedArticle> ProcessedArticles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuggestedEvent> SuggestedEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoSurveillanceConfig> AutoSurveillanceConfigs { get; set; }
    }
}
