//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels.Zebra
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcquisitionMode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcquisitionMode()
        {
            this.Xtbl_Disease_AcquisitionMode = new HashSet<Xtbl_Disease_AcquisitionMode>();
        }
    
        public int AcquisitionModeId { get; set; }
        public int DiseaseVectorId { get; set; }
        public int TransferModalityId { get; set; }
        public Nullable<int> Multiplier { get; set; }
        public Nullable<bool> IsDirect { get; set; }
        public string AcquisitionModeLabel { get; set; }
        public string AcquisitionModeDefinitionLabel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Xtbl_Disease_AcquisitionMode> Xtbl_Disease_AcquisitionMode { get; set; }
    }
}
