//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels.Zebra
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveGeoname
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActiveGeoname()
        {
            this.Xtbl_Article_Location_Disease = new HashSet<Xtbl_Article_Location_Disease>();
            this.Xtbl_Event_Location = new HashSet<Xtbl_Event_Location>();
            this.Xtbl_Event_Location_history = new HashSet<Xtbl_Event_Location_history>();
        }
    
        public int GeonameId { get; set; }
        public string Name { get; set; }
        public Nullable<int> LocationType { get; set; }
        public Nullable<int> Admin1GeonameId { get; set; }
        public Nullable<int> CountryGeonameId { get; set; }
        public string DisplayName { get; set; }
        public string Alternatenames { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public string FeatureCode { get; set; }
        public string CountryName { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<long> Population { get; set; }
        public Nullable<int> SearchSeq2 { get; set; }
        public System.Data.Entity.Spatial.DbGeography Shape { get; set; }
        public Nullable<decimal> LatPopWeighted { get; set; }
        public Nullable<decimal> LongPopWeighted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Xtbl_Article_Location_Disease> Xtbl_Article_Location_Disease { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Xtbl_Event_Location> Xtbl_Event_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Xtbl_Event_Location_history> Xtbl_Event_Location_history { get; set; }
    }
}
