//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels.Zebra
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventSourceAirportSpreadMd
    {
        public int EventId { get; set; }
        public int SourceStationId { get; set; }
        public string StationName { get; set; }
        public string StationCode { get; set; }
        public string CityDisplayName { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> NumCtryAirports { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<int> CtryRank { get; set; }
        public Nullable<int> WorldRank { get; set; }
        public Nullable<double> MinCaseOverPop { get; set; }
        public Nullable<double> MaxCaseOverPop { get; set; }
        public Nullable<double> MinPrevelance { get; set; }
        public Nullable<double> MaxPrevelance { get; set; }
        public Nullable<decimal> MinProb { get; set; }
        public Nullable<decimal> MaxProb { get; set; }
        public Nullable<decimal> MinExpVolume { get; set; }
        public Nullable<decimal> MaxExpVolume { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
