//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels.Zebra
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExternalId
    {
        public string ExternalName { get; set; }
        public string ExternalId { get; set; }
        public string UserId { get; set; }
        public System.DateTimeOffset LastCommunicationDate { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
