//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels.Zebra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xtbl_Disease_CustomGroup
    {
        public int DiseaseId { get; set; }
        public int GroupId { get; set; }
    
        public virtual CustomGroup CustomGroup { get; set; }
    }
}
