//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels.Zebra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xtbl_Event_Location_history
    {
        public int EventId { get; set; }
        public int EventDateType { get; set; }
        public int GeonameId { get; set; }
        public System.DateTime EventDate { get; set; }
        public Nullable<int> SuspCases { get; set; }
        public Nullable<int> ConfCases { get; set; }
        public Nullable<int> RepCases { get; set; }
        public Nullable<int> Deaths { get; set; }
    
        public virtual ActiveGeoname ActiveGeoname { get; set; }
        public virtual Event Event { get; set; }
    }
}
