//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels.Zebra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xtbl_Disease_AcquisitionMode
    {
        public int DiseaseId { get; set; }
        public int SpeciesId { get; set; }
        public int AcquisitionModeId { get; set; }
        public int AcquisitionModeRank { get; set; }
    
        public virtual AcquisitionMode AcquisitionMode { get; set; }
    }
}
