CREATE TABLE [bd].[HUFFMODEL25KMWORLDHEXAGON] (
    [gridId]   NVARCHAR (12)    NOT NULL,
	[population] int NULL,
    [SHAPE]    [sys].[geography] NULL,
	CONSTRAINT [PK_HUFFMODEL25KMWORLDHEXAGON] PRIMARY KEY CLUSTERED ([gridId] ASC)
);

GO

CREATE SPATIAL INDEX [SIndx_huffmodel_SHAPE] ON bd.HUFFMODEL25KMWORLDHEXAGON
(
	SHAPE
)USING  GEOGRAPHY_AUTO_GRID 
WITH (
CELLS_PER_OBJECT = 12, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO