//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Surveillance.SyncConsole.Client.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HealthmapEntities : DbContext
    {
        public HealthmapEntities()
            : base("name=HealthmapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        [DbFunction("HealthmapEntities", "healthmap_getBdLocation_fn")]
        public virtual IQueryable<healthmap_getBdLocation_fn_Result> healthmap_getBdLocation_fn(string locationName)
        {
            var locationNameParameter = locationName != null ?
                new ObjectParameter("LocationName", locationName) :
                new ObjectParameter("LocationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<healthmap_getBdLocation_fn_Result>("[HealthmapEntities].[healthmap_getBdLocation_fn](@LocationName)", locationNameParameter);
        }
    }
}
