//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Surveillance.SyncConsole.Client.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class healthmap_AlertArticlesContent
    {
        public string ArticleId { get; set; }
        public string FullDescription { get; set; }
        public string mainSource { get; set; }
        public string mainSourceUrl { get; set; }
    
        public virtual healthmap_AlertArticles healthmap_AlertArticles { get; set; }
    }
}
