//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Surveillance.SyncConsole.Client.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurveillanceEntities : DbContext
    {
        public SurveillanceEntities()
            : base("name=SurveillanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProcessedArticle> ProcessedArticles { get; set; }
        public virtual DbSet<Xtbl_Article_Location_Disease> Xtbl_Article_Location_Disease { get; set; }
        public virtual DbSet<Geoname> Geonames { get; set; }
        public virtual DbSet<ArticleFeed> ArticleFeeds { get; set; }
        public virtual DbSet<Disease> Diseases { get; set; }
    }
}
