//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Surveillance.SyncConsole.Client.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xtbl_Article_Location_Disease
    {
        public string ArticleId { get; set; }
        public int LocationGeoNameId { get; set; }
        public int DiseaseId { get; set; }
        public Nullable<int> TotalDeathCount { get; set; }
        public Nullable<int> TotalConfirmedCount { get; set; }
        public Nullable<int> TotalSuspectedCount { get; set; }
        public Nullable<int> TotalReportedCount { get; set; }
        public Nullable<int> NewDeathCount { get; set; }
        public Nullable<int> NewConfirmedCount { get; set; }
        public Nullable<int> NewSuspectedCount { get; set; }
        public Nullable<int> NewReportedCount { get; set; }
    
        public virtual ProcessedArticle ProcessedArticle { get; set; }
        public virtual Geoname Geoname { get; set; }
        public virtual Disease Disease { get; set; }
    }
}
