//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Diseases.SyncConsole.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BiodProductSourceModelEntities : DbContext
    {
        public BiodProductSourceModelEntities()
            : base("name=BiodProductSourceModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Nullable<bool>> usp_GeorgeGetDiseaseMapUpdateInfo(string serviceBaseUrlProd, Nullable<int> mapId)
        {
            var serviceBaseUrlProdParameter = serviceBaseUrlProd != null ?
                new ObjectParameter("serviceBaseUrlProd", serviceBaseUrlProd) :
                new ObjectParameter("serviceBaseUrlProd", typeof(string));
    
            var mapIdParameter = mapId.HasValue ?
                new ObjectParameter("mapId", mapId) :
                new ObjectParameter("mapId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("usp_GeorgeGetDiseaseMapUpdateInfo", serviceBaseUrlProdParameter, mapIdParameter);
        }
    }
}
