//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Diseases.SyncConsole.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseaseConditionsMaxValue
    {
        public int OBJECTID { get; set; }
        public int GeonameId { get; set; }
        public short Seasonality_Zone { get; set; }
        public Nullable<short> Urban_GridCode { get; set; }
        public Nullable<decimal> Developed { get; set; }
        public decimal D1_prev { get; set; }
        public decimal D2_prev { get; set; }
        public decimal D3_prev { get; set; }
        public decimal D4_prev { get; set; }
        public decimal D5_prev { get; set; }
        public decimal D6_prev { get; set; }
        public decimal D7_prev { get; set; }
        public decimal D8_prev { get; set; }
        public decimal D9_prev { get; set; }
        public decimal D10_prev { get; set; }
        public decimal D11_prev { get; set; }
        public decimal D12_prev { get; set; }
        public decimal D13_prev { get; set; }
        public decimal D14_prev { get; set; }
        public decimal D15_prev { get; set; }
        public decimal D16_prev { get; set; }
        public decimal D17_prev { get; set; }
        public decimal D18_prev { get; set; }
        public decimal D19_prev { get; set; }
        public decimal D20_prev { get; set; }
        public decimal D21_prev { get; set; }
        public decimal D22_prev { get; set; }
        public decimal D23_prev { get; set; }
        public decimal D24_prev { get; set; }
        public decimal D25_prev { get; set; }
        public decimal D26_prev { get; set; }
        public decimal D27_prev { get; set; }
        public decimal D28_prev { get; set; }
        public decimal D29_prev { get; set; }
        public decimal D30_prev { get; set; }
        public decimal D31_prev { get; set; }
        public decimal D32_prev { get; set; }
        public decimal D33_prev { get; set; }
        public decimal D34_prev { get; set; }
        public decimal D35_prev { get; set; }
        public decimal D36_prev { get; set; }
        public decimal D37_prev { get; set; }
        public decimal D38_prev { get; set; }
        public decimal D39_prev { get; set; }
        public decimal D40_prev { get; set; }
        public decimal D41_prev { get; set; }
        public decimal D42_prev { get; set; }
        public decimal D43_prev { get; set; }
        public decimal D44_prev { get; set; }
        public decimal D45_prev { get; set; }
        public decimal D46_prev { get; set; }
        public decimal D47_prev { get; set; }
        public decimal D48_prev { get; set; }
        public decimal D49_prev { get; set; }
        public decimal D50_prev { get; set; }
        public decimal D51_prev { get; set; }
        public decimal D52_prev { get; set; }
        public decimal D53_prev { get; set; }
        public decimal D54_prev { get; set; }
        public decimal D55_prev { get; set; }
        public decimal D56_prev { get; set; }
        public decimal D57_prev { get; set; }
        public decimal D58_prev { get; set; }
        public decimal D59_prev { get; set; }
        public decimal D60_prev { get; set; }
        public decimal D61_prev { get; set; }
        public decimal D62_prev { get; set; }
        public decimal D63_prev { get; set; }
        public decimal D64_prev { get; set; }
        public decimal D65_prev { get; set; }
        public decimal D66_prev { get; set; }
        public decimal D67_prev { get; set; }
        public decimal D68_prev { get; set; }
        public decimal D69_prev { get; set; }
        public decimal D70_prev { get; set; }
        public decimal D71_prev { get; set; }
        public decimal D72_prev { get; set; }
        public decimal D73_prev { get; set; }
        public decimal D74_prev { get; set; }
        public decimal D75_prev { get; set; }
        public decimal D76_prev { get; set; }
        public decimal D77_prev { get; set; }
        public decimal D78_prev { get; set; }
        public decimal D80_prev { get; set; }
        public decimal D81_prev { get; set; }
        public decimal D82_prev { get; set; }
        public decimal D83_prev { get; set; }
        public decimal D84_prev { get; set; }
        public decimal D85_prev { get; set; }
        public decimal D86_prev { get; set; }
        public decimal D87_prev { get; set; }
        public decimal D88_prev { get; set; }
        public decimal D89_prev { get; set; }
        public decimal D90_prev { get; set; }
        public decimal D91_prev { get; set; }
        public decimal D92_prev { get; set; }
        public decimal D95_prev { get; set; }
        public decimal D98_prev { get; set; }
        public decimal D101_prev { get; set; }
        public decimal D103_prev { get; set; }
        public decimal D104_prev { get; set; }
        public decimal D107_prev { get; set; }
        public decimal D108_prev { get; set; }
        public decimal D109_prev { get; set; }
        public decimal D110_prev { get; set; }
    }
}
