//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Diseases.SyncConsole.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseaseConditions_GCS
    {
        public int OBJECTID { get; set; }
        public Nullable<short> Urban_GridCode { get; set; }
        public Nullable<int> Sanitation_Level { get; set; }
        public Nullable<decimal> Water_Quality { get; set; }
        public Nullable<short> Seasonality_Zone { get; set; }
        public Nullable<decimal> Developed { get; set; }
        public Nullable<decimal> D63_prev { get; set; }
        public Nullable<decimal> D51_prev { get; set; }
        public Nullable<decimal> D82_prev { get; set; }
        public Nullable<decimal> D64_prev { get; set; }
        public Nullable<decimal> D24_prev { get; set; }
        public Nullable<decimal> D52_prev { get; set; }
        public Nullable<decimal> D60_prev { get; set; }
        public Nullable<decimal> D15_prev { get; set; }
        public Nullable<decimal> D3_prev { get; set; }
        public Nullable<decimal> D20_prev { get; set; }
        public Nullable<decimal> D25_prev { get; set; }
        public Nullable<decimal> D98_prev { get; set; }
        public Nullable<decimal> D90_prev { get; set; }
        public Nullable<decimal> D109_prev { get; set; }
        public Nullable<decimal> D48_prev { get; set; }
        public Nullable<decimal> D77_prev { get; set; }
        public Nullable<decimal> D83_prev { get; set; }
        public Nullable<decimal> D36_prev { get; set; }
        public Nullable<decimal> D75_prev { get; set; }
        public Nullable<decimal> D21_prev { get; set; }
        public Nullable<decimal> D85_prev { get; set; }
        public Nullable<decimal> D68_prev { get; set; }
        public Nullable<decimal> D42_prev { get; set; }
        public Nullable<decimal> D35_prev { get; set; }
        public Nullable<decimal> D87_prev { get; set; }
        public Nullable<decimal> D6_prev { get; set; }
        public Nullable<decimal> D46_prev { get; set; }
        public Nullable<decimal> D8_prev { get; set; }
        public Nullable<decimal> D62_prev { get; set; }
        public Nullable<decimal> D55_prev { get; set; }
        public Nullable<decimal> D22_prev { get; set; }
        public Nullable<decimal> D23_prev { get; set; }
        public Nullable<decimal> D78_prev { get; set; }
        public Nullable<decimal> D44_prev { get; set; }
        public Nullable<decimal> D38_prev { get; set; }
        public Nullable<decimal> D74_prev { get; set; }
        public Nullable<decimal> D91_prev { get; set; }
        public Nullable<decimal> D72_prev { get; set; }
        public Nullable<decimal> D31_prev { get; set; }
        public Nullable<decimal> D41_prev { get; set; }
        public Nullable<decimal> D70_prev { get; set; }
        public Nullable<decimal> D27_prev { get; set; }
        public Nullable<decimal> D101_prev { get; set; }
        public Nullable<decimal> D104_prev { get; set; }
        public Nullable<decimal> D18_prev { get; set; }
        public Nullable<decimal> D61_prev { get; set; }
        public Nullable<decimal> D108_prev { get; set; }
        public Nullable<decimal> D54_prev { get; set; }
        public Nullable<decimal> D53_prev { get; set; }
        public Nullable<decimal> D7_prev { get; set; }
        public Nullable<decimal> D45_prev { get; set; }
        public Nullable<decimal> D1_prev { get; set; }
        public Nullable<decimal> D73_prev { get; set; }
        public Nullable<decimal> D39_prev { get; set; }
        public Nullable<decimal> D86_prev { get; set; }
        public Nullable<decimal> D71_prev { get; set; }
        public Nullable<decimal> D67_prev { get; set; }
        public Nullable<decimal> D29_prev { get; set; }
        public Nullable<decimal> D17_prev { get; set; }
        public Nullable<decimal> D47_prev { get; set; }
        public Nullable<decimal> D81_prev { get; set; }
        public Nullable<decimal> D14_prev { get; set; }
        public Nullable<decimal> D34_prev { get; set; }
        public Nullable<decimal> D10_prev { get; set; }
        public Nullable<decimal> D57_prev { get; set; }
        public Nullable<decimal> D103_prev { get; set; }
        public Nullable<decimal> D92_prev { get; set; }
        public Nullable<decimal> D13_prev { get; set; }
        public Nullable<decimal> D26_prev { get; set; }
        public Nullable<decimal> D65_prev { get; set; }
        public Nullable<decimal> D32_prev { get; set; }
        public Nullable<decimal> D84_prev { get; set; }
        public Nullable<decimal> D37_prev { get; set; }
        public Nullable<decimal> D28_prev { get; set; }
        public Nullable<decimal> D66_prev { get; set; }
        public Nullable<decimal> D59_prev { get; set; }
        public Nullable<decimal> D110_prev { get; set; }
        public Nullable<decimal> D9_prev { get; set; }
        public Nullable<decimal> D30_prev { get; set; }
        public Nullable<decimal> D33_prev { get; set; }
        public Nullable<decimal> D19_prev { get; set; }
        public Nullable<decimal> D4_prev { get; set; }
        public Nullable<decimal> D50_prev { get; set; }
        public Nullable<decimal> D11_prev { get; set; }
        public Nullable<decimal> D16_prev { get; set; }
        public Nullable<decimal> D89_prev { get; set; }
        public Nullable<decimal> D80_prev { get; set; }
        public Nullable<decimal> D12_prev { get; set; }
        public Nullable<decimal> D2_prev { get; set; }
        public Nullable<decimal> D40_prev { get; set; }
        public Nullable<decimal> D69_prev { get; set; }
        public Nullable<decimal> D88_prev { get; set; }
        public Nullable<decimal> D43_prev { get; set; }
        public Nullable<decimal> D58_prev { get; set; }
        public Nullable<decimal> D76_prev { get; set; }
        public Nullable<decimal> D107_prev { get; set; }
        public Nullable<decimal> D49_prev { get; set; }
        public Nullable<decimal> D95_prev { get; set; }
        public Nullable<decimal> D56_prev { get; set; }
        public Nullable<decimal> D5_prev { get; set; }
        public Nullable<short> Country_Water_Quality { get; set; }
        public Nullable<decimal> ShapeSTArea__ { get; set; }
        public Nullable<decimal> ShapeSTLength__ { get; set; }
        public System.Data.Entity.Spatial.DbGeography Shape { get; set; }
    }
}
