//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels.ClientHealthmap
{
    using System;
    using System.Collections.Generic;
    
    public partial class healthmap_Disease
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public healthmap_Disease()
        {
            this.healthmap_AlertArticles = new HashSet<healthmap_AlertArticles>();
        }
    
        public short DiseaseId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<short> IsOfInterest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<healthmap_AlertArticles> healthmap_AlertArticles { get; set; }
    }
}
