//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Zebra.Library.EntityModels.ClientHealthmap
{
    using System;
    using System.Collections.Generic;
    
    public partial class healthmap_AlertSourceType
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Alias { get; set; }
    }
}
