//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biod.Surveillance.Models.Surveillance
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeonameAlternatenameEng
    {
        public int GeonameId { get; set; }
        public string AlternatenameEng { get; set; }
        public Nullable<int> LocationType { get; set; }
    
        public virtual Geoname Geoname { get; set; }
    }
}
