CREATE TABLE [bd].[HUFFMODEL25KMWORLDHEXAGON](
	[OBJECTID] [int] IDENTITY(1,1) NOT NULL,
	[gridId] [nvarchar](12) NULL,
	[SHAPE] [geometry] NULL,
    PRIMARY KEY CLUSTERED 
(
	[OBJECTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
