CREATE TABLE [bd].[DiseaseTiers](
	[DiseaseId] [int] NOT NULL,
	[TierId] [int] NOT NULL,
	[Tier] [varchar](50) NULL,
 CONSTRAINT [PK_DiseaseTiers] PRIMARY KEY CLUSTERED 
(
	[DiseaseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO;

